language: php

# As of May 2019, Travis is deprecating VMs based on Precise, which means that we can only test on php >= 5.6 going forward
# (nb: this is not necessarily true yet - and we can use a different base for each php version, but we'll have to
# adapt composer.json plus the apache / env setup scripts to accommodate that...)
dist: xenial

php:
  #- 5.3
  #- 5.4
  #- 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_install:
  # @todo stop useless daemons to save memory: snapd, dockerd, ...
  # This is mandatory or the 'apt-get install' calls following will fail
  - sudo apt-get update -qq
  # Just in case there are git misconfigurations: make sure scripts are executable
  - sudo chmod 755 ./tests/ci/setup/*.sh
  - sudo ./tests/ci/setup/setup_apache.sh
  - ./tests/ci/setup/setup_php_travis.sh

install:
  - composer install

before_script:
  # Output what version of phpunit we got going
  #- ./vendor/bin/phpunit --version
  # Enable code coverage for a single version of php
  - if [ "$TRAVIS_PHP_VERSION" = "7.4" ]; then ./tests/ci/setup/setup_code_coverage.sh enable && export PHPUNIT_OPTS="--coverage-clover=coverage.clover"; fi

script:
    ./vendor/bin/phpunit -v $PHPUNIT_OPTS tests

after_failure:
  # Troubleshoot test env build problems
  #- ps auxwww
  #- 'sudo find /etc/php | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"'
  #- php -i
  #- ls -la /run/php
  #- ls -ltr /var/log
  #- sudo ls -ltr /var/log/apache2
  #- 'sudo find /etc/apache2 | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"'

  # Show as much info as we can to help developers
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/apache2/other_vhosts_access.log
  - sudo cat /var/log/php*.log

after_script:
  # Upload code-coverage to Scrutinizer
  - if [ -f coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
  # Upload code-coverage CodeClimate - disabled as it does not support php 8 atm
  #- if [ -f coverage.clover ]; then CODECLIMATE_REPO_TOKEN=7fa6ee01e345090e059e5e42f3bfbcc8692feb8340396382dd76390a3019ac13 ./vendor/bin/test-reporter --coverage-report=coverage.clover; fi

# reduce depth (history) of git checkout
git:
    depth: 1
